apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-container
          image: koukaazza/picloud-repository
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/picloud
            - name: SPRING_DATASOURCE_USERNAME
              value:
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

          ports:
            - containerPort: 8080



